"""add case performance metrics

Revision ID: 48f046c88ea9
Revises:bb3651646f94
Create Date: 2026-10-05 16:04:37.947111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f046c88ea9'
down_revision: Union[str, Sequence[str], None] = 'bb3651646f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "support_cases",
        sa.Column(
            "classification_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "retrieval_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "generation_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "escalation_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "total_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_cases', 'total_ms')
    op.drop_column('support_cases', 'escalation_ms')
    op.drop_column('support_cases', 'generation_ms')
    op.drop_column('support_cases', 'retrieval_ms')
    op.drop_column('support_cases', 'classification_ms')
    # ### end Alembic commands ###
