"""create support case tables

Revision ID: bb3651646f94
Revises:
Create Date: 2026-10-05 14:17:44.288036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3651646f94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "support_cases",
        sa.Column(
            "classification_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "retrieval_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "generation_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "escalation_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    op.add_column(
        "support_cases",
        sa.Column(
            "total_ms",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_retrievals_case_id'), table_name='case_retrievals')
    op.drop_table('case_retrievals')
    op.drop_index(op.f('ix_case_events_event_type'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_created_at'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_support_cases_status'), table_name='support_cases')
    op.drop_index(op.f('ix_support_cases_should_escalate'), table_name='support_cases')
    op.drop_index(op.f('ix_support_cases_intent'), table_name='support_cases')
    op.drop_index(op.f('ix_support_cases_created_at'), table_name='support_cases')
    op.drop_index(op.f('ix_support_cases_case_id'), table_name='support_cases')
    op.drop_table('support_cases')
    # ### end Alembic commands ###
