"""add escalation reason code

Revision ID: ca0199fd16e1
Revises: 48f046c88ea9
Create Date: 2026-10-07 11:40:05.997851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0199fd16e1'
down_revision: Union[str, Sequence[str], None] = '48f046c88ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "support_cases",
        sa.Column(
            "escalation_reason_code",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE support_cases
        SET escalation_reason_code =
            CASE
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'Customer request could not be mapped%'
                    THEN 'other_unclear'
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'Intent classification confidence%'
                    THEN 'low_confidence'
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'No historical resolution evidence%'
                    THEN 'no_retrieval_evidence'
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'Retrieved historical examples%'
                    THEN 'low_retrieval_similarity'
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'Financial or security-sensitive%'
                    THEN 'financial_security_risk'
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'Customer reports a delivery marked%'
                    THEN 'delivered_not_received'
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'Customer reports a repeated%'
                    THEN 'repeated_unresolved'
                WHEN should_escalate = 1
                    AND escalation_reason LIKE 'Refund issue is described%'
                    THEN 'long_pending_refund'
                ELSE 'auto_handled'
            END
        WHERE escalation_reason_code IS NULL
        """
    )

    # Existing rows have now been backfilled.
    # Keep the column nullable for this migration because SQLite has
    # limitations around altering an existing column to NOT NULL.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_cases', 'escalation_reason_code')
    # ### end Alembic commands ###
